ALTER TYPE "AccommodationType" ADD VALUE IF NOT EXISTS 'COTTAGE';

ALTER TABLE "Activity" ADD COLUMN "publishAt" TIMESTAMP(3);
ALTER TABLE "Experience" ADD COLUMN "publishAt" TIMESTAMP(3);

ALTER TABLE "MenuCategory"
    ADD COLUMN "status" "PublishStatus" NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN "publishAt" TIMESTAMP(3),
    ADD COLUMN "deletedAt" TIMESTAMP(3),
    ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX "MenuCategory_status_sortOrder_idx" ON "MenuCategory"("status", "sortOrder");

ALTER TABLE "MenuItem"
    ALTER COLUMN "isPublished" SET DEFAULT false,
    ADD COLUMN "status" "PublishStatus" NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN "publishAt" TIMESTAMP(3),
    ADD COLUMN "deletedAt" TIMESTAMP(3),
    ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "MenuItem" SET "isPublished" = false;

ALTER TABLE "Testimonial" ADD COLUMN "publishAt" TIMESTAMP(3), ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Testimonial" SET "status" = 'DRAFT' WHERE "consentConfirmed" = false;

ALTER TABLE "PostCategory"
    ADD COLUMN "deletedAt" TIMESTAMP(3),
    ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Faq"
    ALTER COLUMN "isPublished" SET DEFAULT false,
    ADD COLUMN "status" "PublishStatus" NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN "publishAt" TIMESTAMP(3),
    ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Faq" SET "isPublished" = false;
