export const PERMISSIONS = [
  "dashboard.read",
  "cms.read",
  "cms.write",
  "cms.publish",
  "cms.delete",
  "media.read",
  "media.write",
  "media.delete",
  "bookings.read",
  "bookings.write",
  "bookings.confirm",
  "bookings.cancel",
  "payments.record",
  "availability.write",
  "enquiries.read",
  "enquiries.write",
  "leads.read",
  "leads.write",
  "leads.assign",
  "leads.export",
  "customers.read",
  "customers.write",
  "customers.export",
  "rewards.videos.read",
  "rewards.videos.review",
  "rewards.rules.read",
  "rewards.rules.write",
  "rewards.ledger.read",
  "rewards.adjust",
  "rewards.adjust.approve",
  "rewards.reverse",
  "coupons.read",
  "coupons.revoke",
  "seo.write",
  "settings.read",
  "settings.write",
  "staff.read",
  "staff.write",
  "roles.write",
  "audit.read",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSION_MATRIX = {
  "Super Admin": [...PERMISSIONS],
  "Owner/Manager": PERMISSIONS.filter(
    (key) => key !== "roles.write" && key !== "staff.write",
  ),
  Reservations: [
    "bookings.read",
    "bookings.write",
    "bookings.cancel",
    "payments.record",
    "availability.write",
    "enquiries.read",
    "enquiries.write",
    "leads.read",
    "leads.write",
    "leads.assign",
    "customers.read",
  ],
  "Content Editor": [
    "cms.read",
    "cms.write",
    "cms.delete",
    "media.read",
    "media.write",
    "media.delete",
    "seo.write",
  ],
  "Reward Moderator": [
    "rewards.videos.read",
    "rewards.videos.review",
    "rewards.ledger.read",
  ],
  "Read-only": PERMISSIONS.filter((key) => key.endsWith(".read")),
} as const satisfies Record<string, readonly Permission[]>;

export type RoleName = keyof typeof ROLE_PERMISSION_MATRIX;
